// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRARleI7cPK07NJz54RfR6one1_4nLZfI',
    appId: '1:787729844006:web:862ff633fa7ae7001c63e7',
    messagingSenderId: '787729844006',
    projectId: 'loginproject1-18d3c',
    authDomain: 'loginproject1-18d3c.firebaseapp.com',
    storageBucket: 'loginproject1-18d3c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzQdJbqPbA6XGiD5HOiHqoQb9J064bj5s',
    appId: '1:787729844006:android:6cc71c82624c1f4e1c63e7',
    messagingSenderId: '787729844006',
    projectId: 'loginproject1-18d3c',
    storageBucket: 'loginproject1-18d3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhdETMfgidwzGR4FWz4oNSkIxzaGSYRy8',
    appId: '1:787729844006:ios:df81539ec5286f131c63e7',
    messagingSenderId: '787729844006',
    projectId: 'loginproject1-18d3c',
    storageBucket: 'loginproject1-18d3c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1test2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhdETMfgidwzGR4FWz4oNSkIxzaGSYRy8',
    appId: '1:787729844006:ios:c22c734dfcf293a91c63e7',
    messagingSenderId: '787729844006',
    projectId: 'loginproject1-18d3c',
    storageBucket: 'loginproject1-18d3c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1test2.RunnerTests',
  );
}
